# Num-Ex 예제
## 시퀀스 데이터로부터 배열 생성

In [1]:
import numpy as np

In [2]:
data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [3]:
a1.dtype

dtype('int32')

In [8]:
a3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a3.shape

(3, 3)

# 범위를 지정해 배열 생성

○arr_obj = np.arange([start, ] stop[, step])
- start부터 stop 전까지 step만큼 더해 배열을 생성
- start 디폴트는 0
- step 디폴트는 1

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
a1 = np.arange(1,10)
a1.shape

(9,)

In [10]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.array(['1,5','0.62','2'])

array(['1,5', '0.62', '2'], dtype='<U4')

In [16]:
str_a1 = np.array(['1.567', '0.123', '5.123', '9', '8'])
num_a1 = str_a1.astype(float)
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [17]:
str_a2 = np.array(['1','2','3'])
num_a2 = str_a2.astype(int)
num_a2

array([1, 2, 3])

In [18]:
str_a2.dtype

dtype('<U1')

In [19]:
num_a2.dtype

dtype('int32')

In [20]:
np.random.randint(10,size=(3,4))

array([[2, 0, 8, 3],
       [2, 4, 3, 5],
       [2, 6, 1, 1]])

In [24]:
np.random.randint(1,30)

10

In [25]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])

In [26]:
arr1/arr2

array([10., 10., 10., 10.])

In [27]:
arr1/(arr2**2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

In [28]:
arr1>20

array([False, False,  True,  True])

In [29]:
a1 = np.array([0,10,20,30,40,50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [30]:
a1[0
]

0

In [31]:
a1[4]

40

In [32]:
a1[5]=70
a1

array([ 0, 10, 20, 30, 40, 70])

In [35]:
a1[[1,3,5,4]]

array([10, 30, 70, 40])

In [36]:
a2 = np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [37]:
a2[0,2]

30

In [38]:
a2[2,2]=95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [40]:
a2[1] =0

In [41]:
a2[1]

array([0, 0, 0])

In [42]:
a2

array([[10, 20, 30],
       [ 0,  0,  0],
       [70, 80, 95]])

In [43]:
 a2[[0,2],[0,1]]

array([10, 80])

[[1,2],[3,4]] -> [1,3],[2,4] 두개 추출


In [46]:
b2 = np.arange(10,100,10).reshape(3,3)

In [48]:
b2[1:3,1:3]

array([[50, 60],
       [80, 90]])